# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f627256cf79bffb35eb3045ca86421cbdc9a87208cd88d9247f7d4410e6697e64aad82f326672edc939a7dd1ed4ebfa27c08d04b70d5c217191b24fe0745366f

test:
  secret_key_base: 3c82c05d51cc55124619b28ad892bbfc97cb2544592c20b443bab52e5e6ea76be51bfbc4a99d2691ac115e4e123e0011e6ed4c42a430dbbbdbb466a730ccf751

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
